apiVersion: v1
entries:
  cno-agent:
  - apiVersion: v2
    appVersion: v2.0.0-beta
    created: "2023-05-02T14:11:56.618073272Z"
    dependencies:
    - alias: metrics-server
      condition: cnoAgent.metricServer
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server
      version: 3.8.2
    description: Chart for CNO agent
    digest: 55810f44aa1e614b10ba1606fd0fa406572de75c347c49f0cbe058d356f63613
    name: cno-agent
    type: application
    urls:
    - https://beopencloud.github.io/cno/cno-agent-v2.0.0-beta.tgz
    version: v2.0.0-beta
  metrics-server:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: "Allow probes to be turned off completly (this is not advised unless you know what you're doing)."
    apiVersion: v2
    appVersion: 0.6.1
    created: "2023-05-02T14:11:56.618950795Z"
    description: Metrics Server is a scalable, efficient source of container resource
      metrics for Kubernetes built-in autoscaling pipelines.
    digest: 4358fb2014c1e8311653d9495216555e4897db28464b95c96619b0be94b253ec
    home: https://github.com/kubernetes-sigs/metrics-server
    icon: https://avatars.githubusercontent.com/u/36015203?s=400&v=4
    keywords:
    - kubernetes
    - metrics-server
    - metrics
    maintainers:
    - name: stevehipwell
      url: https://github.com/stevehipwell
    - name: krmichel
      url: https://github.com/krmichel
    - name: endrec
      url: https://github.com/endrec
    name: metrics-server
    sources:
    - https://github.com/kubernetes-sigs/metrics-server
    type: application
    urls:
    - https://beopencloud.github.io/cno/charts/metrics-server-3.8.2.tgz
    version: 3.8.2
generated: "2023-05-02T14:11:56.611570204Z"
