apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: cno-notification
  name: cno-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cno-notification
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cno-notification
    spec:
      containers:
      - image: beopenit/cno-notification:v0.0.1-aplpha
        name: cno-ui-notification
        imagePullPolicy: Always
        volumeMounts:
        - name: kafkaconfig
          mountPath: "/usr/src/app/.key"
          readOnly: true
        env:
          - name: PORT
            value: "3000"
        envFrom:
        - configMapRef:
            name: cno-config
        resources: {}
      volumes:
      - name: kafkaconfig
        secret:
          secretName: kafkaconfig
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: cno-notification
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    run: cno-notification
  sessionAffinity: None
  type: ClusterIP
