apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIUf5a/8jrYE8G+bh6cCcmCQe/RKDEwDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIa2V5Y2xvYWswHhcNMjIwMzE4MTE0ODM3WhcNNDkwODAz
    MTE0ODM3WjATMREwDwYDVQQDDAhrZXljbG9hazCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBANSnvPfDkF4E2+SVXSXp8rvdM8uvM3WUwmWu8rsTbnVHRZaY
    R0B8gcSv9yYxeaQnyRpEBj40+EiHYJw+2gpSBCeW4GrXxN3YZpRRhBgj5GEuBR/q
    LapGnkLQkXYjONYFg7D/hlA5XCGbisXyg3f3s1l2zvosSIAPLCvqrizXjGFESqR1
    SO5bNvU6piHnWO1rwNybgSA0CGmMpFNS6/GgNLU8Ibxc6lr2HWye7PFyMrJhpYvX
    LSAfNm5aM1L59q4um5B3i8bKCzoXYQBpZOQJpovePxMn8mmeHr+RdUeTRIevjhal
    QwqRPhCl4Ux+7iakqEkU77O8jV3Yns1cpBSGQSsCAwEAAaNkMGIwDwYDVR0RBAgw
    BocECgAGsjAdBgNVHQ4EFgQU41VrAkJj5XhSSgs8cYD0xZAKG3kwHwYDVR0jBBgw
    FoAU41VrAkJj5XhSSgs8cYD0xZAKG3kwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG
    9w0BAQsFAAOCAQEAJ9xQEWE9UbvXDUoaj+JaEc7UcCfkYCH9QkgrAASQLMfPfDzd
    hmwvEn94vzAUi0Yg+cxwFF7iBANbpsRu16Sqr4pyRzz0WXhj3DnhQJGkJxUqSk/G
    2/AvdopM43o589yaju37nHS7i36y/PGM4gk5aNC3HrOhuiNE92ekgKqQ52NouWj6
    /C6fJUn5ZBqM1OxgYqYS54vNxchfOJd543+O9HXL8rtK/lNZRovsLTXqJzA21daO
    2DzFSuqf2OO8ASiRIOrSekROFVKBLdTtfY8HwyKLw18Sco25xfcBfslKOaAhFeXM
    pz6lz0COXjPf4NZqsuilnEcBqN09iwL08OS06A==
    -----END CERTIFICATE-----
  ca.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA1Ke898OQXgTb5JVdJenyu90zy68zdZTCZa7yuxNudUdFlphH
    QHyBxK/3JjF5pCfJGkQGPjT4SIdgnD7aClIEJ5bgatfE3dhmlFGEGCPkYS4FH+ot
    qkaeQtCRdiM41gWDsP+GUDlcIZuKxfKDd/ezWXbO+ixIgA8sK+quLNeMYURKpHVI
    7ls29TqmIedY7WvA3JuBIDQIaYykU1Lr8aA0tTwhvFzqWvYdbJ7s8XIysmGli9ct
    IB82blozUvn2ri6bkHeLxsoLOhdhAGlk5Ammi94/EyfyaZ4ev5F1R5NEh6+OFqVD
    CpE+EKXhTH7uJqSoSRTvs7yNXdiezVykFIZBKwIDAQABAoIBAEkJl3iNXY89If0f
    Y8+6y1jEv55sfUMcJaxg6xNfuCdlpDv17zrxyGwyd7NReNLtqz9vL6m77a6TeJYR
    bDfxNWYXhtqLYx1CzvCQEstrwGu0L6RnfOmnuYF/OwaVUFcJq9Jl4M669K7CSmZ0
    Rb01gQ7wJGR+QyRgka4/uzTBj4B0ID2Rkt3fsZzBaQ67b9cv0U7BjLWdr0fQQvbz
    trgRBVxRrBNyZwCxEz4ALdgVdYfOKfPncN7R5BPA+/32lJmsxXYcmg51o7s9l10f
    0XZKDLgXzHYdoS0IBlijCPuWs5lbWqCpMF/G0ObQybMG3tjPak7GuR/qSDQtEAn5
    6qSsqPECgYEA/sqCDBUPZQhy78q78Oc9q6/d76dYZuLaEZvWrrgh+6nBqhW2LHjf
    b8Ug4QonhLAdQRmNE1Wlz1Iuiim5nnv080y6YepSyUO9c8ybJFOmXPklp1yeivAB
    jYv3SZF0UwgHaiqet7uJbjgXvzO6GrFrJuClMG6fKF32dPkbXL3ea9kCgYEA1aoM
    WEaktSgrve+q5Mrw1Q6uxDHfhZOTxuUJ61Es0dzwUttzqNGhcaAhDKPG22V6s8kK
    OzPWqhdNVv17C/Vitoz7VsvOuhxG/qEfgdtDa2U+uODbAPjUirvq21Rn2uBrtuu4
    d3Cos4T3K6QYheVoPJvvI8pqcmFwoiVkYXqUhqMCgYB/4Cs83SUI1CC7cMi6s5Qk
    IvQEX7zihmBkDg7FSezkXeKw9oyj7VZWxl0mFO6Yjbtg/O3tEkNRtjFdbmuWuyfJ
    JG02z2AVW0YuZDZJGSKZ7wGS6c04dhSRcfn+ll4HfjQaeKGIHTtwcf6ZG+D/nKPm
    s0C0+hAvNlmHg67T8Qc8oQKBgC77nIlQx2kaczvp1q9GvNxsxRtZSChsQiOLO7ol
    +HARYDsoDG/D4PdGWd4YqWKXFvsvqvNHu91dEGGfjY4coF858w6r9EJSc34MWgxI
    9bNI6RjoQOAe10XGeqdOESQ9ExJ/FOoWuNH43A0ZoVbYEiq5s0UwfmW2bXkKNd+F
    f+F3AoGBAMJvNdsmI0cjwppUoVB7yRUMMWjkfZwapxMHGPWpppA96fcjiLdLf3Pd
    YfRnVsC8PVlz6TmnHimn/gER0xhmeL9cE0+2nXKsA1KEkMrqX/jNkSRa93Nnh3ec
    EIPH6T0Qe63EMqB3bZPwczY9UGOLLbLzX/iBIzp2B/0ZWsVGClzc
    -----END RSA PRIVATE KEY-----
kind: ConfigMap
metadata:
  name: keycloak-configmap