apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIUf5a/8jrYE8G+bh6cCcmCQe/RKDEwDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIa2V5Y2xvYWswHhcNMjIwMzE4MTE0ODM3WhcNNDkwODAz
    MTE0ODM3WjATMREwDwYDVQQDDAhrZXljbG9hazCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBANSnvPfDkF4E2+SVXSXp8rvdM8uvM3WUwmWu8rsTbnVHRZaY
    R0B8gcSv9yYxeaQnyRpEBj40+EiHYJw+2gpSBCeW4GrXxN3YZpRRhBgj5GEuBR/q
    LapGnkLQkXYjONYFg7D/hlA5XCGbisXyg3f3s1l2zvosSIAPLCvqrizXjGFESqR1
    SO5bNvU6piHnWO1rwNybgSA0CGmMpFNS6/GgNLU8Ibxc6lr2HWye7PFyMrJhpYvX
    LSAfNm5aM1L59q4um5B3i8bKCzoXYQBpZOQJpovePxMn8mmeHr+RdUeTRIevjhal
    QwqRPhCl4Ux+7iakqEkU77O8jV3Yns1cpBSGQSsCAwEAAaNkMGIwDwYDVR0RBAgw
    BocECgAGsjAdBgNVHQ4EFgQU41VrAkJj5XhSSgs8cYD0xZAKG3kwHwYDVR0jBBgw
    FoAU41VrAkJj5XhSSgs8cYD0xZAKG3kwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG
    9w0BAQsFAAOCAQEAJ9xQEWE9UbvXDUoaj+JaEc7UcCfkYCH9QkgrAASQLMfPfDzd
    hmwvEn94vzAUi0Yg+cxwFF7iBANbpsRu16Sqr4pyRzz0WXhj3DnhQJGkJxUqSk/G
    2/AvdopM43o589yaju37nHS7i36y/PGM4gk5aNC3HrOhuiNE92ekgKqQ52NouWj6
    /C6fJUn5ZBqM1OxgYqYS54vNxchfOJd543+O9HXL8rtK/lNZRovsLTXqJzA21daO
    2DzFSuqf2OO8ASiRIOrSekROFVKBLdTtfY8HwyKLw18Sco25xfcBfslKOaAhFeXM
    pz6lz0COXjPf4NZqsuilnEcBqN09iwL08OS06A==
    -----END CERTIFICATE-----
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEHTCCAwWgAwIBAgIUYLLdUyjlO7luU37r02TjEQHKHYAwDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIa2V5Y2xvYWswHhcNMjIwMzE4MTE1MzM1WhcNNDkwODAz
    MTE1MzM1WjBhMQswCQYDVQQGEwJTTjEOMAwGA1UECAwFRGFrYXIxDjAMBgNVBAcM
    BURha2FyMREwDwYDVQQKDAhCZU9wZW5JVDEMMAoGA1UECwwDQ05PMREwDwYDVQQD
    DAhrZXljbG9hazCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKTpgBlq
    +H7sEEN+F4GST4oOQdK+mej9q2ZM0fmIaQUC1AfQC45yc4AKqwuT3ctv09gCTsXu
    rcfy+C2YgoCZ8aAjJE84GdRoSKGFb1TqHDU3aYFMQS2Gp2bYmn0TC9Gz13hVY7J2
    LEo4fqWlOQoxq3mPx7IQKeIy4rPC0dRw9ui/coPR+AUydJ6/604YipELoqugOc6e
    PwwCt1gZkSgeoX0I51fWyfGZU4YQPan6P1Gv/GIQ6G/uJiPaZIi7Yu67Hw9Phlzo
    k3v2fsK6D1MrwriwJ4sO0J0KSfVEoJ+sDuySKiakIZ+mR4aV0zAQaQ8Tam2Meiax
    UuZqpb8e+C6zbpcCAwEAAaOCARkwggEVME4GA1UdIwRHMEWAFONVawJCY+V4UkoL
    PHGA9MWQCht5oRekFTATMREwDwYDVQQDDAhrZXljbG9ha4IUf5a/8jrYE8G+bh6c
    CcmCQe/RKDEwCQYDVR0TBAIwADALBgNVHQ8EBAMCBDAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMIGLBgNVHREEgYMwgYCCCGtleWNsb2FrghNrZXljbG9h
    ay5jbm8tc3lzdGVtghdrZXljbG9hay5jbm8tc3lzdGVtLnN2Y4Ifa2V5Y2xvYWsu
    Y25vLXN5c3RlbS5zdmMuY2x1c3RlcoIla2V5Y2xvYWsuY25vLXN5c3RlbS5zdmMu
    Y2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAQCxKqxYJ01IVitnsMPFM
    Fpe5wnAFMwn04OyqLspET6kLP8nIRONTInr4YoZ0Ro/fsNg/oTxMw2A5EAuF6OtR
    Go1P8UoYi5K7qzF8EqGr/grTOuSfa9MdBnCMB5wcCsPXZiM5ZPjuMHrMgVnpaUZE
    1rxIKUUw0pKWICVoZRfO1sG+NVpzCBarHmRKQYvrVk/WUWcS9VvVgtXOQ1P2xVKA
    2WjX1of5TDKEbCqVXn1EqYS0EsT1KN47BJjR4lfBTgeDFQ8ZThnJ0mCsnU9KZ/tB
    8H4IM7UJ/77ajyQfUPLE6Ipc9vNkdgOHBb0ootyKfFRu7BHZoSMXfUZ/pGcKAbnj
    NQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: keycloak-certificate
  namespace: $NAMESPACE