apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: $NAMESPACE
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHRENDQWdDZ0F3SUJBZ0lVZjVhLzhqcllF
    OEcrYmg2Y0NjbUNRZS9SS0RFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lh
    MlY1WTJ4dllXc3dIaGNOTWpJd016RTRNVEUwT0RNM1doY05ORGt3T0RBegpNVEUwT0RNM1dqQVRN
    UkV3RHdZRFZRUUREQWhyWlhsamJHOWhhekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBB
    RENDQVFvQ2dnRUJBTlNudlBmRGtGNEUyK1NWWFNYcDhydmRNOHV2TTNXVXdtV3U4cnNUYm5WSFJa
    YVkKUjBCOGdjU3Y5eVl4ZWFRbnlScEVCajQwK0VpSFlKdysyZ3BTQkNlVzRHclh4TjNZWnBSUmhC
    Z2o1R0V1QlIvcQpMYXBHbmtMUWtYWWpPTllGZzdEL2hsQTVYQ0diaXNYeWczZjNzMWwyenZvc1NJ
    QVBMQ3Zxcml6WGpHRkVTcVIxClNPNWJOdlU2cGlIbldPMXJ3TnliZ1NBMENHbU1wRk5TNi9HZ05M
    VThJYnhjNmxyMkhXeWU3UEZ5TXJKaHBZdlgKTFNBZk5tNWFNMUw1OXE0dW01QjNpOGJLQ3pvWFlR
    QnBaT1FKcG92ZVB4TW44bW1lSHIrUmRVZVRSSWV2amhhbApRd3FSUGhDbDRVeCs3aWFrcUVrVTc3
    TzhqVjNZbnMxY3BCU0dRU3NDQXdFQUFhTmtNR0l3RHdZRFZSMFJCQWd3CkJvY0VDZ0FHc2pBZEJn
    TlZIUTRFRmdRVTQxVnJBa0pqNVhoU1NnczhjWUQweFpBS0cza3dId1lEVlIwakJCZ3cKRm9BVTQx
    VnJBa0pqNVhoU1NnczhjWUQweFpBS0cza3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtp
    Rwo5dzBCQVFzRkFBT0NBUUVBSjl4UUVXRTlVYnZYRFVvYWorSmFFYzdVY0Nma1lDSDlRa2dyQUFT
    UUxNZlBmRHpkCmhtd3ZFbjk0dnpBVWkwWWcrY3h3RkY3aUJBTmJwc1J1MTZTcXI0cHlSenowV1ho
    ajNEbmhRSkdrSnhVcVNrL0cKMi9BdmRvcE00M281ODl5YWp1MzduSFM3aTM2eS9QR000Z2s1YU5D
    M0hyT2h1aU5FOTJla2dLcVE1Mk5vdVdqNgovQzZmSlVuNVpCcU0xT3hnWXFZUzU0dk54Y2hmT0pk
    NTQzK085SFhMOHJ0Sy9sTlpSb3ZzTFRYcUp6QTIxZGFPCjJEekZTdXFmMk9POEFTaVJJT3JTZWtS
    T0ZWS0JMZFR0Zlk4SHd5S0x3MThTY28yNXhmY0Jmc2xLT2FBaEZlWE0KcHo2bHowQ09YalBmNE5a
    cXN1aWxuRWNCcU4wOWl3TDA4T1MwNkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMUtlODk4T1FY
    Z1RiNUpWZEplbnl1OTB6eTY4emRaVENaYTd5dXhOdWRVZEZscGhIClFIeUJ4Sy8zSmpGNXBDZkpH
    a1FHUGpUNFNJZGduRDdhQ2xJRUo1YmdhdGZFM2RobWxGR0VHQ1BrWVM0Rkgrb3QKcWthZVF0Q1Jk
    aU00MWdXRHNQK0dVRGxjSVp1S3hmS0RkL2V6V1hiTytpeElnQThzSytxdUxOZU1ZVVJLcEhWSQo3
    bHMyOVRxbUllZFk3V3ZBM0p1QklEUUlhWXlrVTFMcjhhQTB0VHdodkZ6cVd2WWRiSjdzOFhJeXNt
    R2xpOWN0CklCODJibG96VXZuMnJpNmJrSGVMeHNvTE9oZGhBR2xrNUFtbWk5NC9FeWZ5YVo0ZXY1
    RjFSNU5FaDYrT0ZxVkQKQ3BFK0VLWGhUSDd1SnFTb1NSVHZzN3lOWGRpZXpWeWtGSVpCS3dJREFR
    QUJBb0lCQUVrSmwzaU5YWTg5SWYwZgpZOCs2eTFqRXY1NXNmVU1jSmF4ZzZ4TmZ1Q2RscER2MTd6
    cnh5R3d5ZDdOUmVOTHRxejl2TDZtNzdhNlRlSllSCmJEZnhOV1lYaHRxTFl4MUN6dkNRRXN0cndH
    dTBMNlJuZk9tbnVZRi9Pd2FWVUZjSnE5Smw0TTY2OUs3Q1NtWjAKUmIwMWdRN3dKR1IrUXlSZ2th
    NC91elRCajRCMElEMlJrdDNmc1p6QmFRNjdiOWN2MFU3QmpMV2RyMGZRUXZiegp0cmdSQlZ4UnJC
    Tnlad0N4RXo0QUxkZ1ZkWWZPS2ZQbmNON1I1QlBBKy8zMmxKbXN4WFljbWc1MW83czlsMTBmCjBY
    WktETGdYekhZZG9TMElCbGlqQ1B1V3M1bGJXcUNwTUYvRzBPYlF5Yk1HM3RqUGFrN0d1Ui9xU0RR
    dEVBbjUKNnFTc3FQRUNnWUVBL3NxQ0RCVVBaUWh5NzhxNzhPYzlxNi9kNzZkWVp1TGFFWnZXcnJn
    aCs2bkJxaFcyTEhqZgpiOFVnNFFvbmhMQWRRUm1ORTFXbHoxSXVpaW01bm52MDgweTZZZXBTeVVP
    OWM4eWJKRk9tWFBrbHAxeWVpdkFCCmpZdjNTWkYwVXdnSGFpcWV0N3VKYmpnWHZ6TzZHckZySnVD
    bE1HNmZLRjMyZFBrYlhMM2VhOWtDZ1lFQTFhb00KV0Vha3RTZ3J2ZStxNU1ydzFRNnV4REhmaFpP
    VHh1VUo2MUVzMGR6d1V0dHpxTkdoY2FBaERLUEcyMlY2czhrSwpPelBXcWhkTlZ2MTdDL1ZpdG96
    N1Zzdk91aHhHL3FFZmdkdERhMlUrdU9EYkFQalVpcnZxMjFSbjJ1QnJ0dXU0CmQzQ29zNFQzSzZR
    WWhlVm9QSnZ2SThwcWNtRndvaVZrWVhxVWhxTUNnWUIvNENzODNTVUkxQ0M3Y01pNnM1UWsKSXZR
    RVg3emlobUJrRGc3RlNlemtYZUt3OW95ajdWWld4bDBtRk82WWpidGcvTzN0RWtOUnRqRmRibXVX
    dXlmSgpKRzAyejJBVlcwWXVaRFpKR1NLWjd3R1M2YzA0ZGhTUmNmbitsbDRIZmpRYWVLR0lIVHR3
    Y2Y2WkcrRC9uS1BtCnMwQzAraEF2TmxtSGc2N1Q4UWM4b1FLQmdDNzduSWxReDJrYWN6dnAxcTlH
    dk54c3hSdFpTQ2hzUWlPTE83b2wKK0hBUllEc29ERy9ENFBkR1dkNFlxV0tYRnZzdnF2Tkh1OTFk
    RUdHZmpZNGNvRjg1OHc2cjlFSlNjMzRNV2d4SQo5Yk5JNlJqb1FPQWUxMFhHZXFkT0VTUTlFeEov
    Rk9vV3VOSDQzQTBab1ZiWUVpcTVzMFV3Zm1XMmJYa0tOZCtGCmYrRjNBb0dCQU1Kdk5kc21JMGNq
    d3BwVW9WQjd5UlVNTVdqa2Zad2FweE1IR1BXcHBwQTk2ZmNqaUxkTGYzUGQKWWZSblZzQzhQVmx6
    NlRtbkhpbW4vZ0VSMHhobWVMOWNFMCsyblhLc0ExS0VrTXJxWC9qTmtTUmE5M05uaDNlYwpFSVBI
    NlQwUWU2M0VNcUIzYlpQd2N6WTlVR09MTGJMelgvaUJJenAyQi8wWldzVkdDbHpjCi0tLS0tRU5E
    IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==