apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base

patchesStrategicMerge:
- kafka-patch.yaml
- cno-ui-ingress-deletion-patch.yaml
- cno-api-ingress-deletion-patch.yaml
- cno-ui-deployment-patch.yaml
- keycloak-postgresql-patch.yaml
resources:
- route.yaml
- cno-scc.yaml