---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.onboarding.beopenit.com
spec:
  group: onboarding.beopenit.com
  names:
    kind: Environment
    listKind: EnvironmentList
    plural: environments
    singular: environment
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Environment is the Schema for the environments API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: EnvironmentSpec defines the desired state of Environment
              properties:
                name:
                  type: string
                isprod:
                  type: boolean
                resources:
                  description: Resources describes requests and limits for the cluster
                    resources.
                  properties:
                    limits:
                      description: ResourceDescription describes CPU and memory resources
                        defined for a cluster.
                      properties:
                        cpu:
                          pattern: ^(\d+m|\d+(\.\d{1,3})?)$
                          type: string
                        ephemeral-storage:
                          pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                          type: string
                        memory:
                          pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                          type: string
                      required:
                        - cpu
                        - ephemeral-storage
                        - memory
                      type: object
                    requests:
                      description: ResourceDescription describes CPU and memory resources
                        defined for a cluster.
                      properties:
                        cpu:
                          pattern: ^(\d+m|\d+(\.\d{1,3})?)$
                          type: string
                        ephemeral-storage:
                          pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                          type: string
                        memory:
                          pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                          type: string
                      required:
                        - cpu
                        - ephemeral-storage
                        - memory
                      type: object
                  type: object
                storage:
                  pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                  type: string
                users:
                  items:
                    properties:
                      email:
                        type: string
                      environmentId:
                        type: string
                      userId:
                        type: string
                      role:
                        type: string
                      userFullName:
                        type: string
                      username:
                        type: string
                    required:
                      - email
                      - environmentId
                      - userId
                      - role
                      - userFullName
                      - username
                    type: object
                  type: array
              required:
                - name
                - resources
                - storage
                - users
              type: object
            status:
              description: EnvironmentStatus defines the observed state of Environment
                (success, failed)
              properties:
                environmentStatus:
                  type: string
              required:
                - environmentStatus
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
