apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: False
    host: keycloak
    tlsTermination: passthrough
  podDisruptionBudget:
    enabled: True
  externalDatabase:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Djboss.as.management.blocking.timeout=600"
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "false"
      volumes:
        items:
        - name: cno-realm
          mountPath: /cno
          configMaps:
            - cno-realm
        items:
        - name: keycloak
          secret: keycloak
          mountPath: /etc/x509/https
        items:  
        - name: keycloak-certificate
          mountPath: /cno
          configMaps:
            - keycloak-certificate

      env:
        - name: KEYCLOAK_IMPORT
          value: /cno/cno-realm.json
      env:
        - name: X509_CA_BUNDLE
          value: "/cno/ca.crt /cno/server.crt"
          