apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cno-ui
  name: cno-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cno-ui
  template:
    metadata:
      labels:
        app: cno-ui
    spec:
      containers:
      - image: {{ .Values.cnoUi.image | default "beopenit/cno-ui:1.0.0-rc" }}
        name: cno-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: API_URL
          value: https://cno-api.{{ $.Values.expose.domain }}
        - name: NOTIFICATION_URL
          value: https://cno-notification.{{ $.Values.expose.domain }}
        - name: OIDC_URL
          value: OIDC_URL
        - name: OIDC_REALM
          value: OIDC_REALM
        - name: OIDC_CLIENT_ID
          value: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          value: ""